Dockerfiles adjustments and hadolint
pawelekg95/pygrm pull request #3
Opened 2022-10-03 12:33 UTC by pawelekg95

* Separated default dockerfile on different architectures
* Added hadolint do dockerfiles
* Hadolint suggestions implemented
* Added job to automatically verify dockerfiles
* Adjusted install command to allow providing custom dockerfile

2022-10-03 13:43 UTC, Majroch requested changes
nie chce mi się dalej przechodzić

2022-10-03 13:43 UTC, Majroch commented on app/device/remote.py
> +    def cpu_architecture(self) -> Tuple[Error, str, str]:
a nie obiekt `Output` byłby lepszy? po co zwracać tuple? Można zwrócić zwykły DTO i z niego pobrać rezultat

2022-10-03 13:43 UTC, Majroch commented on app/device/remote.py
> +        arch = architectures[stdout.strip('\n')]
co tutaj będzie przekazane jako klucz do array? lepiej byłoby to pobrać w osobnej zmiennej i potem tutaj przekazać

2022-10-03 13:43 UTC, Majroch commented on app/terminal/commands/install_runner.py
> +            default_image = input('Use default image? [yes / no] ')
```suggestion
            default_image = input('Use default image? [yes / no] ').lower()
```

2022-10-03 13:43 UTC, Majroch commented on app/terminal/commands/install_runner.py
> +                '/images/github-runner_' + cpu_arch.strip('\n') + '.dockerfile' \
wywaliłbym to do innej funkcji, mało czytelny kod

2022-10-03 13:43 UTC, Majroch commented on images/github-runner_amd64.dockerfile
> +    apt-get install -y --no-install-recommends lsb-release=11.1.0ubuntu2 dpkg=1.19.7ubuntu3.2 diffutils=1:3.7-3 && \
to może być jedną komendą, nie trzeba rozbijać

2022-10-03 13:43 UTC, Majroch commented on images/github-runner_amd64.dockerfile
> +    rm -rf /var/lib/apt/lists/*
drugi raz to samo? tutaj nie ma nic z `apt` więc to jest tutaj niepotrzebne

2022-10-03 13:43 UTC, Majroch commented on images/github-runner_amd64.dockerfile
> +    rm -rf /var/lib/apt/lists/*
To nie powinno być wyżej, podczas instalacji innych dependencies?

2022-10-03 13:43 UTC, Majroch commented on images/github-runner_amd64.dockerfile
> +    rm -rf /var/lib/apt/lists/*
Całe powinno być w if'ie, nie trzeba robić `update` i wywalać całego cache'a, kiedy nic nie instalujesz

2022-10-03 13:56 UTC, pawelekg95 commented on images/github-runner_amd64.dockerfile
> +    rm -rf /var/lib/apt/lists/*
Unfortunately, hadolint's statement is differenet:
![image](https://user-images.githubusercontent.com/56723306/193595408-d1133da1-8176-46b1-9921-cd0542a3f2d1.png)

2022-10-03 13:58 UTC, pawelekg95 commented on images/github-runner_amd64.dockerfile
> +    rm -rf /var/lib/apt/lists/*
Wanted to separate distinct stages to be more readable. Moreover, this step relies on RUN from line 63 which uses curl, gpg and tee, so they need to be installed in the first place.

2022-10-03 13:58 UTC, pawelekg95 commented on images/github-runner_amd64.dockerfile
> +    rm -rf /var/lib/apt/lists/*
Hadolint:
![image](https://user-images.githubusercontent.com/56723306/193595408-d1133da1-8176-46b1-9921-cd0542a3f2d1.png)

2022-10-03 13:59 UTC, pawelekg95 commented on app/terminal/commands/install_runner.py
> +                '/images/github-runner_' + cpu_arch.strip('\n') + '.dockerfile' \
Done.

2022-10-03 13:59 UTC, pawelekg95 commented on app/terminal/commands/install_runner.py
> +            default_image = input('Use default image? [yes / no] ')
Done.

2022-10-03 13:59 UTC, pawelekg95 commented on app/device/remote.py
> +        arch = architectures[stdout.strip('\n')]
Done.

2022-10-03 14:06 UTC, pawelekg95 commented on images/github-runner_amd64.dockerfile
> +    apt-get install -y --no-install-recommends lsb-release=11.1.0ubuntu2 dpkg=1.19.7ubuntu3.2 diffutils=1:3.7-3 && \
Done.

2022-10-04 08:13 UTC, pawelekg95 commented on app/device/remote.py
> +    def cpu_architecture(self) -> Tuple[Error, str, str]:
Good point, will adjust it. However this pull request regards dockerfiles and dockerfile linter. Created separate [issue](https://github.com/pawelekg95/pygrm/issues/4) and will adjust it in some next pull requests.

2022-10-09 19:55 UTC, Majroch approved these changes

2022-10-10 12:20 UTC, merged